version: "3.8"
services:
  postgres:
  image: postgres:17
  container_name: petshop-db
  restart: always
  ports:
    - "5435:5434"
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
    POSTGRES_DB: petshop
  volumes:
    - "./pgdata:/var/lib/postgresql/data"
volumes:
  pgdata:
